sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libnacl-dev libconfig-dev libvpx-dev libopus-dev -qq

script:
  - autoreconf -i
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox --enable-nacl --with-nacl-headers=/usr/include/nacl
  - cat config.h
  - make -j3
  - make check
  - make dist

notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#Tox-Qt-GUI"
    on_success: always
    on_failure: always
