sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libconfig-dev libvpx-dev libopus-dev -qq
  # install sodium, as it's not in Ubuntu Trusty yet
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - cd libsodium
  - git checkout tags/1.0.8 > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure > /dev/null
  - make check -j3 > /dev/null
  - sudo make install >/dev/null
  - cd ..
  - sudo ldconfig

script:
  - autoreconf -i
  - CFLAGS="-Ofast -Wall -Wextra" ./configure --enable-daemon --enable-ntox
  - make
  - make check
  - cat build/test-suite.log
  - make dist
    # test bootstrap daemon
  - cp other/bootstrap_daemon/tox-bootstrapd.conf .
  - |
    N=-1 &&
    while grep -q "bootstrap_nodes =" tox-bootstrapd.conf;
    do
      head -n $N other/bootstrap_daemon/tox-bootstrapd.conf > tox-bootstrapd.conf;
      N=$((N-1));
    done
  - python3 other/bootstrap_daemon/docker/get-nodes.py >> tox-bootstrapd.conf
  - cat tox-bootstrapd.conf
  - timeout --preserve-status 5 tox-bootstrapd --config tox-bootstrapd.conf --log-backend stdout --foreground

notifications:
  email: false

  irc:
    channels:
      - "chat.freenode.net#Tox-Qt-GUI"
    on_success: always
    on_failure: always
